<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grupo [
    <!ELEMENT grupo (alumno+)>
    <!ELEMENT alumno (nombreCompleto, fila, edad)>
    <!ATTLIST alumno colorPelo (rubio|castaño) #REQUIRED>
    <!ELEMENT nombreCompleto (nombre, apellidos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT fila (#PCDATA)>
    <!ELEMENT edad EMPTY>
]>
<grupo>
    <alumno colorPelo="rubio">
        <nombreCompleto>
            <nombre>María</nombre>
            <apellidos>López</apellidos>
        </nombreCompleto>
        <fila>1</fila>
        <edad></edad>
    </alumno>

    <alumno colorPelo="castaño">
        <nombreCompleto>
            <nombre>Enrique</nombre>
            <apellidos>Pérez</apellidos>
        </nombreCompleto>
        <fila>3</fila>
        <edad></edad>
    </alumno>

    <alumno colorPelo="rubio">
        <nombreCompleto>
            <nombre>Aurora</nombre>
            <apellidos>Alonso</apellidos>
        </nombreCompleto>
        <fila>2</fila>
        <edad></edad>
    </alumno>
</grupo>