=== rubenacooo/MarkupLangProjects/XML/multinacional.dtd
<!ELEMENT listado (futuro+, divisa+, bono+, letra+)>
<!ATTLIST futuro precio CDATA #REQUIRED>
<!ATTLIST divisa
    precio CDATA #REQUIRED
    estable CDATA #IMPLIED>
<!ATTLIST bono
    precio CDATA #REQUIRED
    estable CDATA #IMPLIED>
<!ATTLIST letra precio CDATA #REQUIRED>
<!ELEMENT futuro (producto, mercado?, ciudad_procedencia)>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT ciudad_procedencia (madrid|nuevayork|frankfurt|tokio)>
<!ELEMENT madrid EMPTY>
<!ELEMENT nuevayork EMPTY>
<!ELEMENT frankfurt EMPTY>
<!ELEMENT tokio EMPTY>
<!ELEMENT bono (pais_de_procedencia, valor_deseado, valor_minimo, valor_maximo, ciudad_procedencia)>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valor_deseado (#PCDATA)>
<!ELEMENT valor_minimo (#PCDATA)>
<!ELEMENT valor_maximo (#PCDATA)>
<!ELEMENT divisa (nombre_divisa, tipo_cambio+, ciudad_procedencia)>
<!ELEMENT nombre_divisa (#PCDATA)>
<!ELEMENT tipo_cambio (#PCDATA)>
<!ELEMENT letra (tipo_interes, pais_emisor, ciudad_procedencia)>
<!ELEMENT tipo_interes (#PCDATA)>
<!ELEMENT pais_emisor (Espania|EEUU|Alemania|Japon)>
<!ELEMENT Espania EMPTY>
<!ELEMENT EEUU EMPTY>
<!ELEMENT Alemania EMPTY>
<!ELEMENT Japon EMPTY>

=== rubenacooo/MarkupLangProjects/XML/multinacional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listado SYSTEM 'multinacional.dtd'>
<listado>
    <futuro precio="4">
        <producto>Pan</producto>
        <mercado>Francia</mercado>
        <ciudad_procedencia>
            <madrid />
        </ciudad_procedencia>
    </futuro>
    <divisa precio="324">
        <nombre_divisa>Dolar</nombre_divisa>
        <tipo_cambio>43224</tipo_cambio>
        <tipo_cambio>36436</tipo_cambio>
        <tipo_cambio>43895</tipo_cambio>
        <ciudad_procedencia>
            <nuevayork />
        </ciudad_procedencia>
    </divisa>
    <bono precio="4376543" estable="si">
        <pais_de_procedencia>Alemania</pais_de_procedencia>
        <valor_deseado>363463</valor_deseado>
        <valor_minimo>123</valor_minimo>
        <valor_maximo>4235</valor_maximo>
        <ciudad_procedencia>
            <frankfurt />
        </ciudad_procedencia>
    </bono>
    <letra precio="87">
        <tipo_interes>34%</tipo_interes>
        <pais_emisor>
            <Japon />
        </pais_emisor>
        <ciudad_procedencia>
            <tokio />
        </ciudad_procedencia>
    </letra>
</listado>
