<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos [
<!ELEMENT productos (producto+)>
<!ELEMENT producto (raton | teclado | monitor)>
<!ELEMENT raton (codigo, nombre?, descripcion?)>
<!ELEMENT teclado (codigo, nombre?, descripcion?)>
<!ELEMENT monitor (codigo, nombre?, descripcion?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
]>

<productos>

    <producto>
        <raton>
            <codigo>22</codigo>
            <nombre>raton</nombre>
            <descripcion>esta guapo</descripcion>
        </raton>
    </producto>

    <producto>
        <monitor>
            <codigo>34</codigo>
            <nombre>monitor</nombre>
            <descripcion>144hz</descripcion>
        </monitor>
    </producto>

</productos>
